[package]
name = "playground-for-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
appwrite = { git = "https://github.com/PineappleIOnic/sdk-for-rust/" }
rand = "0.8.5"
colored = "2.0.0"